export * from './colaborator.entity';
export * from './problem.entity';
export * from './software_program.entity';
export * from './technical_area.entity';
export * from './user.entity';
export * from './solution.entity';
export * from './problem_solutions.entity'
export * from './movement.entity';
export * from './attention.entity';
export * from './ticket.entity';
export * from './file_paths.entity';
export * from './reply.entity';