export enum Configuration {
  API_PORT = 'API_PORT',
  DB_PORT = 'DB_PORT',
  HOST = 'HOST',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  JWT_SECRET = 'JWT_SECRET'
}
